/**
 * This code was generated by "react-native codegen-harmony"
 * 
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 * 
 * @generatorVersion: 1
 */

#include "GtPushModule.h"

namespace rnoh {
using namespace facebook;

GtPushModule::GtPushModule(const ArkTSTurboModule::Context ctx, const std::string name) : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        ARK_METHOD_METADATA(initPush, 0),
        ARK_METHOD_METADATA(turnOnPush, 0),
        ARK_METHOD_METADATA(turnOffPush, 0),
        ARK_METHOD_METADATA(clientId, 1),
        ARK_METHOD_METADATA(version, 1),
        ARK_METHOD_METADATA(setBackgroundOffLine, 1),
        ARK_METHOD_METADATA(bindAlias, 2),
        ARK_METHOD_METADATA(unbindAlias, 3),
        ARK_METHOD_METADATA(setTag, 2),
        ARK_METHOD_METADATA(queryTag, 1),
        ARK_METHOD_METADATA(sendFeedbackMessage, 3),
        ARK_METHOD_METADATA(setSilentTime, 2),
        ARK_METHOD_METADATA(setBadgeNum, 1),
    };
}

} // namespace rnoh
