/**
 * This code was generated by "react-native codegen-harmony"
 * 
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 * 
 * @generatorVersion: 1
 */

#pragma once

#include "RNOH/ArkTSTurboModule.h"

namespace rnoh {

class JSI_EXPORT GtPushModule : public ArkTSTurboModule {
  public:
    GtPushModule(const ArkTSTurboModule::Context ctx, const std::string name);
};

} // namespace rnoh
